---
- name: installing pre-reqs
  apt: name={{ item }} state=present
  with_items:
    - curl
    - ca-certificates
    - postfix

- name: checking to see if gitlab is already installed
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_installed

- name: downloading gitlab deb package
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: 0775
  when: gitlab_installed.stat.exists == false

- name: installing gitlab
  command: /tmp/script.deb.sh
  when: gitlab_installed.stat.exists == false

- name: installing gitlab-ce
  apt: name=gitlab-ce state=present
  when: gitlab_installed.stat.exists == false
  notify:
    - reconfigure gitlab
    - restart gitlab
    - wait for unicorn

#- name: reconfiguring gitlab (first-run)
#  command: gitlab-ctl reconfigure creates=/var/opt/gitlab/bootstrapped
#  when: gitlab_installed.stat.exists == false
