---
# tasks file for ansible-gitlab-ce
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_os_family == "Redhat"

- include: config_gitlab.yml
  tags:
    - config_gitlab
  when: config_gitlab
